import "./importEnvs";

const PORT: string = process.env.PORT;
const ENV: string = process.env.ENV;
const ACCESS_TOKEN_SECRET: string = process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET: string = process.env.REFRESH_TOKEN_SECRET;
const ACCESS_TOKEN_EXPIRY: string = process.env.ACCESS_TOKEN_EXPIRY;
const REFRESH_TOKEN_EXPIRY: string = process.env.REFRESH_TOKEN_EXPIRY;
const ZERO_EX_ADDRESS: string = process.env.ZERO_EX_ADDRESS;
const APP_WALLET_ADDRESS: string = process.env.APP_WALLET_ADDRESS;
const EMAIL_ADDRESS: string = process.env.EMAIL_ADDRESS;
const EMAIL_PASSWORD: string = process.env.EMAIL_PASSWORD
let DB: string;
let FLUTTERWAVE_SECRET_KEY: string;
let FLUTTERWAVE_PUBLIC_KEY: string;
let FLUTTERWAVE_ENCRYPTION_KEY: string;
let STRIPE_PUB_KEY: string;
let STRIPE_SECRET_KEY: string;

if (ENV === "production") {
  DB = process.env.DB_PROD;
  FLUTTERWAVE_PUBLIC_KEY = process.env.FLUTTERWAVE_PUBLIC_KEY_PROD;
  FLUTTERWAVE_SECRET_KEY = process.env.FLUTTERWAVE_SECRET_KEY_PROD;
  FLUTTERWAVE_ENCRYPTION_KEY = process.env.FLUTTERWAVE_ENCRYPTION_KEY_PROD;
  STRIPE_PUB_KEY = process.env.STRIPE_PUB_KEY_PROD;
  STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY_PROD;
} else {
  DB = process.env.DB_DEV;
  FLUTTERWAVE_PUBLIC_KEY = process.env.FLUTTERWAVE_PUBLIC_KEY_DEV;
  FLUTTERWAVE_SECRET_KEY = process.env.FLUTTERWAVE_SECRET_KEY_DEV;
  FLUTTERWAVE_ENCRYPTION_KEY = process.env.FLUTTERWAVE_ENCRYPTION_KEY_DEV;
  STRIPE_PUB_KEY = process.env.STRIPE_PUB_KEY_DEV;
  STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY_DEV;
}

export {
  PORT,
  ENV,
  DB,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  ZERO_EX_ADDRESS,
  FLUTTERWAVE_ENCRYPTION_KEY,
  FLUTTERWAVE_PUBLIC_KEY,
  FLUTTERWAVE_SECRET_KEY,
  STRIPE_PUB_KEY,
  STRIPE_SECRET_KEY,
  APP_WALLET_ADDRESS,
  EMAIL_ADDRESS,
  EMAIL_PASSWORD
};